// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sr_fft_fft_16pt (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_real_0_address0,
        in_real_0_ce0,
        in_real_0_q0,
        in_real_0_address1,
        in_real_0_ce1,
        in_real_0_q1,
        in_real_1_address0,
        in_real_1_ce0,
        in_real_1_q0,
        in_real_1_address1,
        in_real_1_ce1,
        in_real_1_q1,
        in_real_2_address0,
        in_real_2_ce0,
        in_real_2_q0,
        in_real_2_address1,
        in_real_2_ce1,
        in_real_2_q1,
        in_real_3_address0,
        in_real_3_ce0,
        in_real_3_q0,
        in_real_3_address1,
        in_real_3_ce1,
        in_real_3_q1,
        in_imag_0_address0,
        in_imag_0_ce0,
        in_imag_0_q0,
        in_imag_0_address1,
        in_imag_0_ce1,
        in_imag_0_q1,
        in_imag_1_address0,
        in_imag_1_ce0,
        in_imag_1_q0,
        in_imag_1_address1,
        in_imag_1_ce1,
        in_imag_1_q1,
        in_imag_2_address0,
        in_imag_2_ce0,
        in_imag_2_q0,
        in_imag_2_address1,
        in_imag_2_ce1,
        in_imag_2_q1,
        in_imag_3_address0,
        in_imag_3_ce0,
        in_imag_3_q0,
        in_imag_3_address1,
        in_imag_3_ce1,
        in_imag_3_q1,
        out_real_0_address0,
        out_real_0_ce0,
        out_real_0_we0,
        out_real_0_d0,
        out_real_1_address0,
        out_real_1_ce0,
        out_real_1_we0,
        out_real_1_d0,
        out_real_2_address0,
        out_real_2_ce0,
        out_real_2_we0,
        out_real_2_d0,
        out_real_3_address0,
        out_real_3_ce0,
        out_real_3_we0,
        out_real_3_d0,
        out_imag_0_address0,
        out_imag_0_ce0,
        out_imag_0_we0,
        out_imag_0_d0,
        out_imag_1_address0,
        out_imag_1_ce0,
        out_imag_1_we0,
        out_imag_1_d0,
        out_imag_2_address0,
        out_imag_2_ce0,
        out_imag_2_we0,
        out_imag_2_d0,
        out_imag_3_address0,
        out_imag_3_ce0,
        out_imag_3_we0,
        out_imag_3_d0
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [1:0] in_real_0_address0;
output   in_real_0_ce0;
input  [31:0] in_real_0_q0;
output  [1:0] in_real_0_address1;
output   in_real_0_ce1;
input  [31:0] in_real_0_q1;
output  [1:0] in_real_1_address0;
output   in_real_1_ce0;
input  [31:0] in_real_1_q0;
output  [1:0] in_real_1_address1;
output   in_real_1_ce1;
input  [31:0] in_real_1_q1;
output  [1:0] in_real_2_address0;
output   in_real_2_ce0;
input  [31:0] in_real_2_q0;
output  [1:0] in_real_2_address1;
output   in_real_2_ce1;
input  [31:0] in_real_2_q1;
output  [1:0] in_real_3_address0;
output   in_real_3_ce0;
input  [31:0] in_real_3_q0;
output  [1:0] in_real_3_address1;
output   in_real_3_ce1;
input  [31:0] in_real_3_q1;
output  [1:0] in_imag_0_address0;
output   in_imag_0_ce0;
input  [31:0] in_imag_0_q0;
output  [1:0] in_imag_0_address1;
output   in_imag_0_ce1;
input  [31:0] in_imag_0_q1;
output  [1:0] in_imag_1_address0;
output   in_imag_1_ce0;
input  [31:0] in_imag_1_q0;
output  [1:0] in_imag_1_address1;
output   in_imag_1_ce1;
input  [31:0] in_imag_1_q1;
output  [1:0] in_imag_2_address0;
output   in_imag_2_ce0;
input  [31:0] in_imag_2_q0;
output  [1:0] in_imag_2_address1;
output   in_imag_2_ce1;
input  [31:0] in_imag_2_q1;
output  [1:0] in_imag_3_address0;
output   in_imag_3_ce0;
input  [31:0] in_imag_3_q0;
output  [1:0] in_imag_3_address1;
output   in_imag_3_ce1;
input  [31:0] in_imag_3_q1;
output  [1:0] out_real_0_address0;
output   out_real_0_ce0;
output   out_real_0_we0;
output  [31:0] out_real_0_d0;
output  [1:0] out_real_1_address0;
output   out_real_1_ce0;
output   out_real_1_we0;
output  [31:0] out_real_1_d0;
output  [1:0] out_real_2_address0;
output   out_real_2_ce0;
output   out_real_2_we0;
output  [31:0] out_real_2_d0;
output  [1:0] out_real_3_address0;
output   out_real_3_ce0;
output   out_real_3_we0;
output  [31:0] out_real_3_d0;
output  [1:0] out_imag_0_address0;
output   out_imag_0_ce0;
output   out_imag_0_we0;
output  [31:0] out_imag_0_d0;
output  [1:0] out_imag_1_address0;
output   out_imag_1_ce0;
output   out_imag_1_we0;
output  [31:0] out_imag_1_d0;
output  [1:0] out_imag_2_address0;
output   out_imag_2_ce0;
output   out_imag_2_we0;
output  [31:0] out_imag_2_d0;
output  [1:0] out_imag_3_address0;
output   out_imag_3_ce0;
output   out_imag_3_we0;
output  [31:0] out_imag_3_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[1:0] in_real_0_address0;
reg in_real_0_ce0;
reg in_real_0_ce1;
reg[1:0] in_real_1_address0;
reg in_real_1_ce0;
reg in_real_1_ce1;
reg[1:0] in_real_2_address0;
reg in_real_2_ce0;
reg in_real_2_ce1;
reg[1:0] in_real_3_address0;
reg in_real_3_ce0;
reg in_real_3_ce1;
reg[1:0] in_imag_0_address0;
reg in_imag_0_ce0;
reg in_imag_0_ce1;
reg[1:0] in_imag_1_address0;
reg in_imag_1_ce0;
reg in_imag_1_ce1;
reg[1:0] in_imag_2_address0;
reg in_imag_2_ce0;
reg in_imag_2_ce1;
reg[1:0] in_imag_3_address0;
reg in_imag_3_ce0;
reg in_imag_3_ce1;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state3;
reg   [31:0] in_real_0_load_reg_1320;
wire    ap_CS_fsm_state4;
reg   [31:0] in_real_1_load_reg_1325;
reg   [31:0] in_real_2_load_reg_1330;
reg   [31:0] in_real_3_load_reg_1335;
reg   [31:0] in_imag_0_load_reg_1340;
reg   [31:0] in_imag_1_load_reg_1345;
reg   [31:0] in_imag_2_load_reg_1350;
reg   [31:0] in_imag_3_load_reg_1355;
reg   [31:0] in_real_0_load_6_reg_1360;
reg   [31:0] in_real_1_load_6_reg_1365;
reg   [31:0] b_real_V_35_reg_1370;
reg   [31:0] in_real_3_load_6_reg_1375;
reg   [31:0] in_imag_0_load_6_reg_1380;
reg   [31:0] in_imag_1_load_6_reg_1385;
reg   [31:0] in_imag_2_load_6_reg_1390;
reg   [31:0] in_imag_3_load_6_reg_1395;
wire    ap_CS_fsm_state6;
wire   [31:0] e_in_real_V_q1;
reg   [31:0] a_real_V_reg_1440;
wire    ap_CS_fsm_state7;
wire   [31:0] e_in_imag_V_q1;
reg   [31:0] a_imag_V_reg_1446;
wire   [31:0] e_in_real_V_q0;
reg   [31:0] b_real_V_reg_1452;
wire   [31:0] e_in_imag_V_q0;
reg   [31:0] b_imag_V_reg_1458;
wire   [31:0] e_in_real_V_15_q1;
reg   [31:0] a_real_V_41_reg_1464;
wire   [31:0] e_in_imag_V_15_q1;
reg   [31:0] a_imag_V_36_reg_1470;
wire   [31:0] e_in_real_V_15_q0;
reg   [31:0] b_real_V_30_reg_1476;
wire   [31:0] e_in_imag_V_15_q0;
reg   [31:0] b_imag_V_40_reg_1482;
wire   [31:0] r_real_V_fu_776_p2;
reg   [31:0] r_real_V_reg_1528;
wire    ap_CS_fsm_state8;
wire   [31:0] r_imag_V_fu_783_p2;
reg   [31:0] r_imag_V_reg_1533;
wire   [31:0] r_real_V_93_fu_790_p2;
reg   [31:0] r_real_V_93_reg_1538;
wire   [31:0] r_imag_V_106_fu_797_p2;
reg   [31:0] r_imag_V_106_reg_1543;
wire   [31:0] r_real_V_94_fu_804_p2;
reg   [31:0] r_real_V_94_reg_1548;
wire   [31:0] r_imag_V_107_fu_811_p2;
reg   [31:0] r_imag_V_107_reg_1553;
wire   [31:0] r_real_V_95_fu_818_p2;
reg   [31:0] r_real_V_95_reg_1558;
wire   [31:0] r_imag_V_108_fu_825_p2;
reg   [31:0] r_imag_V_108_reg_1563;
wire   [31:0] r_real_V_120_fu_832_p2;
reg   [31:0] r_real_V_120_reg_1568;
wire   [31:0] r_imag_V_135_fu_839_p2;
reg   [31:0] r_imag_V_135_reg_1573;
wire   [31:0] r_real_V_121_fu_846_p2;
reg   [31:0] r_real_V_121_reg_1578;
wire   [31:0] r_imag_V_136_fu_853_p2;
reg   [31:0] r_imag_V_136_reg_1583;
wire   [31:0] r_real_V_122_fu_860_p2;
reg   [31:0] r_real_V_122_reg_1588;
wire   [31:0] r_imag_V_137_fu_867_p2;
reg   [31:0] r_imag_V_137_reg_1593;
wire   [31:0] r_real_V_123_fu_874_p2;
reg   [31:0] r_real_V_123_reg_1598;
wire   [31:0] r_imag_V_138_fu_881_p2;
reg   [31:0] r_imag_V_138_reg_1603;
wire   [31:0] r_real_V_126_fu_984_p2;
reg   [31:0] r_real_V_126_reg_1608;
wire    ap_CS_fsm_state10;
wire   [31:0] r_imag_V_141_fu_991_p2;
reg   [31:0] r_imag_V_141_reg_1613;
wire   [31:0] r_real_V_127_fu_998_p2;
reg   [31:0] r_real_V_127_reg_1618;
wire   [31:0] r_imag_V_142_fu_1005_p2;
reg   [31:0] r_imag_V_142_reg_1623;
wire   [31:0] r_real_V_128_fu_1012_p2;
reg   [31:0] r_real_V_128_reg_1628;
wire   [31:0] r_imag_V_143_fu_1019_p2;
reg   [31:0] r_imag_V_143_reg_1633;
wire   [31:0] r_real_V_129_fu_1026_p2;
reg   [31:0] r_real_V_129_reg_1638;
wire   [31:0] r_imag_V_144_fu_1033_p2;
reg   [31:0] r_imag_V_144_reg_1643;
wire   [31:0] r_real_V_132_fu_1088_p2;
reg   [31:0] r_real_V_132_reg_1648;
wire   [31:0] r_imag_V_147_fu_1095_p2;
reg   [31:0] r_imag_V_147_reg_1653;
wire   [31:0] r_real_V_133_fu_1102_p2;
reg   [31:0] r_real_V_133_reg_1658;
wire   [31:0] r_imag_V_148_fu_1109_p2;
reg   [31:0] r_imag_V_148_reg_1663;
wire   [31:0] r_real_V_134_fu_1116_p2;
reg   [31:0] r_real_V_134_reg_1668;
wire   [31:0] r_imag_V_149_fu_1123_p2;
reg   [31:0] r_imag_V_149_reg_1673;
wire   [31:0] r_real_V_135_fu_1130_p2;
reg   [31:0] r_real_V_135_reg_1678;
wire   [31:0] r_imag_V_150_fu_1137_p2;
reg   [31:0] r_imag_V_150_reg_1683;
reg   [0:0] e_in_real_V_address0;
reg    e_in_real_V_ce0;
reg    e_in_real_V_we0;
wire   [0:0] e_in_real_V_address1;
reg    e_in_real_V_ce1;
reg   [0:0] e_in_real_V_15_address0;
reg    e_in_real_V_15_ce0;
reg    e_in_real_V_15_we0;
wire   [0:0] e_in_real_V_15_address1;
reg    e_in_real_V_15_ce1;
reg   [0:0] e_in_imag_V_address0;
reg    e_in_imag_V_ce0;
reg    e_in_imag_V_we0;
wire   [0:0] e_in_imag_V_address1;
reg    e_in_imag_V_ce1;
reg   [0:0] e_in_imag_V_15_address0;
reg    e_in_imag_V_15_ce0;
reg    e_in_imag_V_15_we0;
wire   [0:0] e_in_imag_V_15_address1;
reg    e_in_imag_V_15_ce1;
reg   [1:0] e_in_real_V_16_address0;
reg    e_in_real_V_16_ce0;
reg    e_in_real_V_16_we0;
wire   [31:0] e_in_real_V_16_q0;
wire   [1:0] e_in_real_V_16_address1;
reg    e_in_real_V_16_ce1;
wire   [31:0] e_in_real_V_16_q1;
reg   [1:0] e_in_real_V_17_address0;
reg    e_in_real_V_17_ce0;
reg    e_in_real_V_17_we0;
wire   [31:0] e_in_real_V_17_q0;
wire   [1:0] e_in_real_V_17_address1;
reg    e_in_real_V_17_ce1;
wire   [31:0] e_in_real_V_17_q1;
reg   [1:0] e_in_imag_V_16_address0;
reg    e_in_imag_V_16_ce0;
reg    e_in_imag_V_16_we0;
wire   [31:0] e_in_imag_V_16_q0;
wire   [1:0] e_in_imag_V_16_address1;
reg    e_in_imag_V_16_ce1;
wire   [31:0] e_in_imag_V_16_q1;
reg   [1:0] e_in_imag_V_17_address0;
reg    e_in_imag_V_17_ce0;
reg    e_in_imag_V_17_we0;
wire   [31:0] e_in_imag_V_17_q0;
wire   [1:0] e_in_imag_V_17_address1;
reg    e_in_imag_V_17_ce1;
wire   [31:0] e_in_imag_V_17_q1;
reg   [1:0] e_out_real_V_address0;
reg    e_out_real_V_ce0;
reg    e_out_real_V_we0;
wire   [31:0] e_out_real_V_q0;
reg    e_out_real_V_ce1;
reg    e_out_real_V_we1;
reg   [1:0] e_out_real_V_1_address0;
reg    e_out_real_V_1_ce0;
reg    e_out_real_V_1_we0;
wire   [31:0] e_out_real_V_1_q0;
reg    e_out_real_V_1_ce1;
reg    e_out_real_V_1_we1;
reg   [1:0] e_out_imag_V_address0;
reg    e_out_imag_V_ce0;
reg    e_out_imag_V_we0;
wire   [31:0] e_out_imag_V_q0;
reg    e_out_imag_V_ce1;
reg    e_out_imag_V_we1;
reg   [1:0] e_out_imag_V_1_address0;
reg    e_out_imag_V_1_ce0;
reg    e_out_imag_V_1_we0;
wire   [31:0] e_out_imag_V_1_q0;
reg    e_out_imag_V_1_ce1;
reg    e_out_imag_V_1_we1;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_ap_start;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_ap_done;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_ap_idle;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_ap_ready;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_imag_V_17_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_imag_V_17_ce0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_imag_V_17_we0;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_imag_V_17_d0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_imag_V_16_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_imag_V_16_ce0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_imag_V_16_we0;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_imag_V_16_d0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_real_V_17_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_real_V_17_ce0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_real_V_17_we0;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_real_V_17_d0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_real_V_16_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_real_V_16_ce0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_real_V_16_we0;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_real_V_16_d0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_real_0_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_real_0_ce0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_real_1_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_real_1_ce0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_real_2_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_real_2_ce0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_real_3_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_real_3_ce0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_imag_0_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_imag_0_ce0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_imag_1_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_imag_1_ce0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_imag_2_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_imag_2_ce0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_imag_3_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_imag_3_ce0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_ap_start;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_ap_done;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_ap_idle;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_ap_ready;
wire   [0:0] grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_15_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_15_ce0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_15_we0;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_15_d0;
wire   [0:0] grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_ce0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_we0;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_d0;
wire   [0:0] grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_15_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_15_ce0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_15_we0;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_15_d0;
wire   [0:0] grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_ce0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_we0;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_d0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_16_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_16_ce0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_17_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_17_ce0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_16_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_16_ce0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_17_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_17_ce0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_ap_start;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_ap_done;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_ap_idle;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_ap_ready;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_real_V_7_out;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_real_V_7_out_ap_vld;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_real_V_6_out;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_real_V_6_out_ap_vld;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_real_V_5_out;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_real_V_5_out_ap_vld;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_real_V_out;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_real_V_out_ap_vld;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_imag_V_7_out;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_imag_V_7_out_ap_vld;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_imag_V_6_out;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_imag_V_6_out_ap_vld;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_imag_V_5_out;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_imag_V_5_out_ap_vld;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_imag_V_out;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_imag_V_out_ap_vld;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_imag_V_7_out;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_imag_V_7_out_ap_vld;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_imag_V_6_out;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_imag_V_6_out_ap_vld;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_imag_V_5_out;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_imag_V_5_out_ap_vld;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_imag_V_out;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_imag_V_out_ap_vld;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_real_V_7_out;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_real_V_7_out_ap_vld;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_real_V_6_out;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_real_V_6_out_ap_vld;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_real_V_5_out;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_real_V_5_out_ap_vld;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_real_V_out;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_real_V_out_ap_vld;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_ap_start;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_ap_done;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_ap_idle;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_ap_ready;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_11_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_11_ce0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_11_we0;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_11_d0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_11_address1;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_11_ce1;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_11_we1;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_11_d1;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_ce0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_we0;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_d0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_address1;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_ce1;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_we1;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_d1;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_11_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_11_ce0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_11_we0;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_11_d0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_11_address1;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_11_ce1;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_11_we1;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_11_d1;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_ce0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_we0;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_d0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_address1;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_ce1;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_we1;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_d1;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_ap_start;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_ap_done;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_ap_idle;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_ap_ready;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_3_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_3_ce0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_3_we0;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_3_d0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_2_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_2_ce0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_2_we0;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_2_d0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_1_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_1_ce0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_1_we0;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_1_d0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_0_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_0_ce0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_0_we0;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_0_d0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_3_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_3_ce0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_3_we0;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_3_d0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_2_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_2_ce0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_2_we0;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_2_d0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_1_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_1_ce0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_1_we0;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_1_d0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_0_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_0_ce0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_0_we0;
wire   [31:0] grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_0_d0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_e_out_real_V_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_e_out_real_V_ce0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_e_out_imag_V_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_e_out_imag_V_ce0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_e_out_real_V_11_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_e_out_real_V_11_ce0;
wire   [1:0] grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_e_out_imag_V_11_address0;
wire    grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_e_out_imag_V_11_ce0;
reg    grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_ap_start_reg;
reg    grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_ap_start_reg;
wire    ap_CS_fsm_state9;
reg    grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_ap_start_reg;
wire    ap_CS_fsm_state11;
wire   [31:0] r_real_V_118_fu_760_p2;
wire   [31:0] r_real_V_116_fu_744_p2;
wire   [31:0] r_imag_V_133_fu_764_p2;
wire   [31:0] r_imag_V_131_fu_748_p2;
wire   [31:0] r_imag_V_134_fu_772_p2;
wire   [31:0] r_real_V_117_fu_752_p2;
wire   [31:0] r_imag_V_132_fu_756_p2;
wire   [31:0] r_real_V_119_fu_768_p2;
wire   [31:0] cpd_real_V_fu_960_p2;
wire   [31:0] r_real_V_124_fu_936_p2;
wire   [31:0] cpd_imag_V_fu_966_p2;
wire   [31:0] r_imag_V_139_fu_942_p2;
wire   [31:0] cmd_imag_V_fu_978_p2;
wire   [31:0] r_real_V_125_fu_948_p2;
wire   [31:0] r_imag_V_140_fu_954_p2;
wire   [31:0] cmd_real_V_fu_972_p2;
wire   [31:0] r_real_V_130_fu_1040_p2;
wire   [31:0] cpd_real_V_1_fu_1064_p2;
wire   [31:0] r_imag_V_145_fu_1046_p2;
wire   [31:0] cpd_imag_V_1_fu_1070_p2;
wire   [31:0] r_real_V_131_fu_1052_p2;
wire   [31:0] cmd_imag_V_1_fu_1082_p2;
wire   [31:0] r_imag_V_146_fu_1058_p2;
wire   [31:0] cmd_real_V_1_fu_1076_p2;
reg   [10:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_block_state5_on_subcall_done;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_ap_start_reg = 1'b0;
#0 grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_ap_start_reg = 1'b0;
#0 grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_ap_start_reg = 1'b0;
#0 grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_ap_start_reg = 1'b0;
#0 grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_ap_start_reg = 1'b0;
end

sr_fft_fft_16pt_e_in_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
e_in_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(e_in_real_V_address0),
    .ce0(e_in_real_V_ce0),
    .we0(e_in_real_V_we0),
    .d0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_d0),
    .q0(e_in_real_V_q0),
    .address1(e_in_real_V_address1),
    .ce1(e_in_real_V_ce1),
    .q1(e_in_real_V_q1)
);

sr_fft_fft_16pt_e_in_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
e_in_real_V_15_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(e_in_real_V_15_address0),
    .ce0(e_in_real_V_15_ce0),
    .we0(e_in_real_V_15_we0),
    .d0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_15_d0),
    .q0(e_in_real_V_15_q0),
    .address1(e_in_real_V_15_address1),
    .ce1(e_in_real_V_15_ce1),
    .q1(e_in_real_V_15_q1)
);

sr_fft_fft_16pt_e_in_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
e_in_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(e_in_imag_V_address0),
    .ce0(e_in_imag_V_ce0),
    .we0(e_in_imag_V_we0),
    .d0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_d0),
    .q0(e_in_imag_V_q0),
    .address1(e_in_imag_V_address1),
    .ce1(e_in_imag_V_ce1),
    .q1(e_in_imag_V_q1)
);

sr_fft_fft_16pt_e_in_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
e_in_imag_V_15_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(e_in_imag_V_15_address0),
    .ce0(e_in_imag_V_15_ce0),
    .we0(e_in_imag_V_15_we0),
    .d0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_15_d0),
    .q0(e_in_imag_V_15_q0),
    .address1(e_in_imag_V_15_address1),
    .ce1(e_in_imag_V_15_ce1),
    .q1(e_in_imag_V_15_q1)
);

sr_fft_fft_16pt_e_in_real_V_16_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
e_in_real_V_16_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(e_in_real_V_16_address0),
    .ce0(e_in_real_V_16_ce0),
    .we0(e_in_real_V_16_we0),
    .d0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_real_V_16_d0),
    .q0(e_in_real_V_16_q0),
    .address1(e_in_real_V_16_address1),
    .ce1(e_in_real_V_16_ce1),
    .q1(e_in_real_V_16_q1)
);

sr_fft_fft_16pt_e_in_real_V_16_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
e_in_real_V_17_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(e_in_real_V_17_address0),
    .ce0(e_in_real_V_17_ce0),
    .we0(e_in_real_V_17_we0),
    .d0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_real_V_17_d0),
    .q0(e_in_real_V_17_q0),
    .address1(e_in_real_V_17_address1),
    .ce1(e_in_real_V_17_ce1),
    .q1(e_in_real_V_17_q1)
);

sr_fft_fft_16pt_e_in_real_V_16_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
e_in_imag_V_16_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(e_in_imag_V_16_address0),
    .ce0(e_in_imag_V_16_ce0),
    .we0(e_in_imag_V_16_we0),
    .d0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_imag_V_16_d0),
    .q0(e_in_imag_V_16_q0),
    .address1(e_in_imag_V_16_address1),
    .ce1(e_in_imag_V_16_ce1),
    .q1(e_in_imag_V_16_q1)
);

sr_fft_fft_16pt_e_in_real_V_16_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
e_in_imag_V_17_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(e_in_imag_V_17_address0),
    .ce0(e_in_imag_V_17_ce0),
    .we0(e_in_imag_V_17_we0),
    .d0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_imag_V_17_d0),
    .q0(e_in_imag_V_17_q0),
    .address1(e_in_imag_V_17_address1),
    .ce1(e_in_imag_V_17_ce1),
    .q1(e_in_imag_V_17_q1)
);

sr_fft_fft_16pt_e_out_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
e_out_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(e_out_real_V_address0),
    .ce0(e_out_real_V_ce0),
    .we0(e_out_real_V_we0),
    .d0(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_d0),
    .q0(e_out_real_V_q0),
    .address1(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_address1),
    .ce1(e_out_real_V_ce1),
    .we1(e_out_real_V_we1),
    .d1(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_d1)
);

sr_fft_fft_16pt_e_out_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
e_out_real_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(e_out_real_V_1_address0),
    .ce0(e_out_real_V_1_ce0),
    .we0(e_out_real_V_1_we0),
    .d0(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_11_d0),
    .q0(e_out_real_V_1_q0),
    .address1(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_11_address1),
    .ce1(e_out_real_V_1_ce1),
    .we1(e_out_real_V_1_we1),
    .d1(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_11_d1)
);

sr_fft_fft_16pt_e_out_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
e_out_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(e_out_imag_V_address0),
    .ce0(e_out_imag_V_ce0),
    .we0(e_out_imag_V_we0),
    .d0(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_d0),
    .q0(e_out_imag_V_q0),
    .address1(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_address1),
    .ce1(e_out_imag_V_ce1),
    .we1(e_out_imag_V_we1),
    .d1(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_d1)
);

sr_fft_fft_16pt_e_out_real_V_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
e_out_imag_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(e_out_imag_V_1_address0),
    .ce0(e_out_imag_V_1_ce0),
    .we0(e_out_imag_V_1_we0),
    .d0(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_11_d0),
    .q0(e_out_imag_V_1_q0),
    .address1(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_11_address1),
    .ce1(e_out_imag_V_1_ce1),
    .we1(e_out_imag_V_1_we1),
    .d1(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_11_d1)
);

sr_fft_fft_16pt_Pipeline_VITIS_LOOP_165_1 grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_ap_start),
    .ap_done(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_ap_done),
    .ap_idle(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_ap_idle),
    .ap_ready(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_ap_ready),
    .e_in_imag_V_17_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_imag_V_17_address0),
    .e_in_imag_V_17_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_imag_V_17_ce0),
    .e_in_imag_V_17_we0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_imag_V_17_we0),
    .e_in_imag_V_17_d0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_imag_V_17_d0),
    .e_in_imag_V_16_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_imag_V_16_address0),
    .e_in_imag_V_16_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_imag_V_16_ce0),
    .e_in_imag_V_16_we0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_imag_V_16_we0),
    .e_in_imag_V_16_d0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_imag_V_16_d0),
    .e_in_real_V_17_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_real_V_17_address0),
    .e_in_real_V_17_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_real_V_17_ce0),
    .e_in_real_V_17_we0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_real_V_17_we0),
    .e_in_real_V_17_d0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_real_V_17_d0),
    .e_in_real_V_16_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_real_V_16_address0),
    .e_in_real_V_16_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_real_V_16_ce0),
    .e_in_real_V_16_we0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_real_V_16_we0),
    .e_in_real_V_16_d0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_real_V_16_d0),
    .in_real_0_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_real_0_address0),
    .in_real_0_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_real_0_ce0),
    .in_real_0_q0(in_real_0_q0),
    .in_real_1_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_real_1_address0),
    .in_real_1_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_real_1_ce0),
    .in_real_1_q0(in_real_1_q0),
    .in_real_2_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_real_2_address0),
    .in_real_2_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_real_2_ce0),
    .in_real_2_q0(in_real_2_q0),
    .in_real_3_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_real_3_address0),
    .in_real_3_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_real_3_ce0),
    .in_real_3_q0(in_real_3_q0),
    .in_imag_0_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_imag_0_address0),
    .in_imag_0_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_imag_0_ce0),
    .in_imag_0_q0(in_imag_0_q0),
    .in_imag_1_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_imag_1_address0),
    .in_imag_1_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_imag_1_ce0),
    .in_imag_1_q0(in_imag_1_q0),
    .in_imag_2_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_imag_2_address0),
    .in_imag_2_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_imag_2_ce0),
    .in_imag_2_q0(in_imag_2_q0),
    .in_imag_3_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_imag_3_address0),
    .in_imag_3_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_imag_3_ce0),
    .in_imag_3_q0(in_imag_3_q0)
);

sr_fft_fft_16pt_Pipeline_VITIS_LOOP_120_1 grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_ap_start),
    .ap_done(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_ap_done),
    .ap_idle(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_ap_idle),
    .ap_ready(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_ap_ready),
    .e_in_imag_V_15_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_15_address0),
    .e_in_imag_V_15_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_15_ce0),
    .e_in_imag_V_15_we0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_15_we0),
    .e_in_imag_V_15_d0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_15_d0),
    .e_in_imag_V_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_address0),
    .e_in_imag_V_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_ce0),
    .e_in_imag_V_we0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_we0),
    .e_in_imag_V_d0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_d0),
    .e_in_real_V_15_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_15_address0),
    .e_in_real_V_15_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_15_ce0),
    .e_in_real_V_15_we0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_15_we0),
    .e_in_real_V_15_d0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_15_d0),
    .e_in_real_V_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_address0),
    .e_in_real_V_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_ce0),
    .e_in_real_V_we0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_we0),
    .e_in_real_V_d0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_d0),
    .e_in_real_V_16_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_16_address0),
    .e_in_real_V_16_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_16_ce0),
    .e_in_real_V_16_q0(e_in_real_V_16_q0),
    .e_in_real_V_17_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_17_address0),
    .e_in_real_V_17_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_17_ce0),
    .e_in_real_V_17_q0(e_in_real_V_17_q0),
    .e_in_imag_V_16_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_16_address0),
    .e_in_imag_V_16_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_16_ce0),
    .e_in_imag_V_16_q0(e_in_imag_V_16_q0),
    .e_in_imag_V_17_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_17_address0),
    .e_in_imag_V_17_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_17_ce0),
    .e_in_imag_V_17_q0(e_in_imag_V_17_q0)
);

sr_fft_fft_16pt_Pipeline_VITIS_LOOP_171_2 grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_ap_start),
    .ap_done(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_ap_done),
    .ap_idle(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_ap_idle),
    .ap_ready(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_ap_ready),
    .in_real_3_load_9(in_real_3_load_6_reg_1375),
    .o2_in_real_V_8(b_real_V_35_reg_1370),
    .in_real_1_load_9(in_real_1_load_6_reg_1365),
    .in_real_0_load_9(in_real_0_load_6_reg_1360),
    .in_imag_0_load_9(in_imag_0_load_6_reg_1380),
    .in_imag_1_load_9(in_imag_1_load_6_reg_1385),
    .o2_in_imag_V_8(in_imag_2_load_6_reg_1390),
    .in_imag_3_load_9(in_imag_3_load_6_reg_1395),
    .in_real_0_load_8(in_real_0_load_reg_1320),
    .in_real_1_load_8(in_real_1_load_reg_1325),
    .in_real_2_load_8(in_real_2_load_reg_1330),
    .in_real_3_load_8(in_real_3_load_reg_1335),
    .in_imag_0_load_8(in_imag_0_load_reg_1340),
    .in_imag_1_load_8(in_imag_1_load_reg_1345),
    .in_imag_2_load_8(in_imag_2_load_reg_1350),
    .in_imag_3_load_8(in_imag_3_load_reg_1355),
    .o2_in_real_V_7_out(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_real_V_7_out),
    .o2_in_real_V_7_out_ap_vld(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_real_V_7_out_ap_vld),
    .o2_in_real_V_6_out(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_real_V_6_out),
    .o2_in_real_V_6_out_ap_vld(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_real_V_6_out_ap_vld),
    .o2_in_real_V_5_out(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_real_V_5_out),
    .o2_in_real_V_5_out_ap_vld(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_real_V_5_out_ap_vld),
    .o2_in_real_V_out(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_real_V_out),
    .o2_in_real_V_out_ap_vld(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_real_V_out_ap_vld),
    .o2_in_imag_V_7_out(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_imag_V_7_out),
    .o2_in_imag_V_7_out_ap_vld(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_imag_V_7_out_ap_vld),
    .o2_in_imag_V_6_out(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_imag_V_6_out),
    .o2_in_imag_V_6_out_ap_vld(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_imag_V_6_out_ap_vld),
    .o2_in_imag_V_5_out(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_imag_V_5_out),
    .o2_in_imag_V_5_out_ap_vld(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_imag_V_5_out_ap_vld),
    .o2_in_imag_V_out(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_imag_V_out),
    .o2_in_imag_V_out_ap_vld(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_imag_V_out_ap_vld),
    .o1_in_imag_V_7_out(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_imag_V_7_out),
    .o1_in_imag_V_7_out_ap_vld(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_imag_V_7_out_ap_vld),
    .o1_in_imag_V_6_out(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_imag_V_6_out),
    .o1_in_imag_V_6_out_ap_vld(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_imag_V_6_out_ap_vld),
    .o1_in_imag_V_5_out(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_imag_V_5_out),
    .o1_in_imag_V_5_out_ap_vld(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_imag_V_5_out_ap_vld),
    .o1_in_imag_V_out(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_imag_V_out),
    .o1_in_imag_V_out_ap_vld(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_imag_V_out_ap_vld),
    .o1_in_real_V_7_out(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_real_V_7_out),
    .o1_in_real_V_7_out_ap_vld(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_real_V_7_out_ap_vld),
    .o1_in_real_V_6_out(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_real_V_6_out),
    .o1_in_real_V_6_out_ap_vld(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_real_V_6_out_ap_vld),
    .o1_in_real_V_5_out(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_real_V_5_out),
    .o1_in_real_V_5_out_ap_vld(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_real_V_5_out_ap_vld),
    .o1_in_real_V_out(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_real_V_out),
    .o1_in_real_V_out_ap_vld(grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_real_V_out_ap_vld)
);

sr_fft_fft_16pt_Pipeline_VITIS_LOOP_131_2 grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_ap_start),
    .ap_done(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_ap_done),
    .ap_idle(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_ap_idle),
    .ap_ready(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_ap_ready),
    .e_out_imag_V_11_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_11_address0),
    .e_out_imag_V_11_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_11_ce0),
    .e_out_imag_V_11_we0(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_11_we0),
    .e_out_imag_V_11_d0(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_11_d0),
    .e_out_imag_V_11_address1(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_11_address1),
    .e_out_imag_V_11_ce1(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_11_ce1),
    .e_out_imag_V_11_we1(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_11_we1),
    .e_out_imag_V_11_d1(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_11_d1),
    .e_out_imag_V_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_address0),
    .e_out_imag_V_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_ce0),
    .e_out_imag_V_we0(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_we0),
    .e_out_imag_V_d0(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_d0),
    .e_out_imag_V_address1(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_address1),
    .e_out_imag_V_ce1(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_ce1),
    .e_out_imag_V_we1(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_we1),
    .e_out_imag_V_d1(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_d1),
    .e_out_real_V_11_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_11_address0),
    .e_out_real_V_11_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_11_ce0),
    .e_out_real_V_11_we0(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_11_we0),
    .e_out_real_V_11_d0(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_11_d0),
    .e_out_real_V_11_address1(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_11_address1),
    .e_out_real_V_11_ce1(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_11_ce1),
    .e_out_real_V_11_we1(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_11_we1),
    .e_out_real_V_11_d1(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_11_d1),
    .e_out_real_V_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_address0),
    .e_out_real_V_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_ce0),
    .e_out_real_V_we0(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_we0),
    .e_out_real_V_d0(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_d0),
    .e_out_real_V_address1(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_address1),
    .e_out_real_V_ce1(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_ce1),
    .e_out_real_V_we1(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_we1),
    .e_out_real_V_d1(grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_d1),
    .r_real_V_126(r_real_V_120_reg_1568),
    .r_real_V_127(r_real_V_121_reg_1578),
    .r_imag_V_141(r_imag_V_135_reg_1573),
    .r_imag_V_142(r_imag_V_136_reg_1583),
    .r_real_V_128(r_real_V_122_reg_1588),
    .r_real_V_129(r_real_V_123_reg_1598),
    .r_imag_V_143(r_imag_V_137_reg_1593),
    .r_imag_V_144(r_imag_V_138_reg_1603),
    .r_real_V(r_real_V_reg_1528),
    .r_real_V_83(r_real_V_93_reg_1538),
    .r_imag_V(r_imag_V_reg_1533),
    .r_imag_V_94(r_imag_V_106_reg_1543),
    .r_real_V_84(r_real_V_94_reg_1548),
    .r_real_V_85(r_real_V_95_reg_1558),
    .r_imag_V_95(r_imag_V_107_reg_1553),
    .r_imag_V_96(r_imag_V_108_reg_1563)
);

sr_fft_fft_16pt_Pipeline_VITIS_LOOP_181_3 grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_ap_start),
    .ap_done(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_ap_done),
    .ap_idle(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_ap_idle),
    .ap_ready(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_ap_ready),
    .out_imag_3_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_3_address0),
    .out_imag_3_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_3_ce0),
    .out_imag_3_we0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_3_we0),
    .out_imag_3_d0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_3_d0),
    .out_imag_2_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_2_address0),
    .out_imag_2_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_2_ce0),
    .out_imag_2_we0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_2_we0),
    .out_imag_2_d0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_2_d0),
    .out_imag_1_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_1_address0),
    .out_imag_1_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_1_ce0),
    .out_imag_1_we0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_1_we0),
    .out_imag_1_d0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_1_d0),
    .out_imag_0_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_0_address0),
    .out_imag_0_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_0_ce0),
    .out_imag_0_we0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_0_we0),
    .out_imag_0_d0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_0_d0),
    .out_real_3_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_3_address0),
    .out_real_3_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_3_ce0),
    .out_real_3_we0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_3_we0),
    .out_real_3_d0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_3_d0),
    .out_real_2_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_2_address0),
    .out_real_2_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_2_ce0),
    .out_real_2_we0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_2_we0),
    .out_real_2_d0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_2_d0),
    .out_real_1_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_1_address0),
    .out_real_1_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_1_ce0),
    .out_real_1_we0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_1_we0),
    .out_real_1_d0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_1_d0),
    .out_real_0_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_0_address0),
    .out_real_0_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_0_ce0),
    .out_real_0_we0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_0_we0),
    .out_real_0_d0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_0_d0),
    .r_real_V_132(r_real_V_126_reg_1608),
    .r_real_V_133(r_real_V_127_reg_1618),
    .r_real_V_134(r_real_V_128_reg_1628),
    .r_real_V_135(r_real_V_129_reg_1638),
    .r_imag_V_147(r_imag_V_141_reg_1613),
    .r_imag_V_148(r_imag_V_142_reg_1623),
    .r_imag_V_149(r_imag_V_143_reg_1633),
    .r_imag_V_150(r_imag_V_144_reg_1643),
    .r_real_V_138(r_real_V_132_reg_1648),
    .r_real_V_139(r_real_V_133_reg_1658),
    .r_real_V_140(r_real_V_134_reg_1668),
    .r_real_V_141(r_real_V_135_reg_1678),
    .r_imag_V_153(r_imag_V_147_reg_1653),
    .r_imag_V_154(r_imag_V_148_reg_1663),
    .r_imag_V_155(r_imag_V_149_reg_1673),
    .r_imag_V_156(r_imag_V_150_reg_1683),
    .e_out_real_V_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_e_out_real_V_address0),
    .e_out_real_V_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_e_out_real_V_ce0),
    .e_out_real_V_q0(e_out_real_V_q0),
    .e_out_imag_V_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_e_out_imag_V_address0),
    .e_out_imag_V_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_e_out_imag_V_ce0),
    .e_out_imag_V_q0(e_out_imag_V_q0),
    .e_out_real_V_11_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_e_out_real_V_11_address0),
    .e_out_real_V_11_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_e_out_real_V_11_ce0),
    .e_out_real_V_11_q0(e_out_real_V_1_q0),
    .e_out_imag_V_11_address0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_e_out_imag_V_11_address0),
    .e_out_imag_V_11_ce0(grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_e_out_imag_V_11_ce0),
    .e_out_imag_V_11_q0(e_out_imag_V_1_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_ap_start_reg <= 1'b1;
        end else if ((grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_ap_ready == 1'b1)) begin
            grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_ap_start_reg <= 1'b1;
        end else if ((grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_ap_ready == 1'b1)) begin
            grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_ap_start_reg <= 1'b1;
        end else if ((grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_ap_ready == 1'b1)) begin
            grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_ap_start_reg <= 1'b1;
        end else if ((grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_ap_ready == 1'b1)) begin
            grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_ap_start_reg <= 1'b1;
        end else if ((grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_ap_ready == 1'b1)) begin
            grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        a_imag_V_36_reg_1470 <= e_in_imag_V_15_q1;
        a_imag_V_reg_1446 <= e_in_imag_V_q1;
        a_real_V_41_reg_1464 <= e_in_real_V_15_q1;
        a_real_V_reg_1440 <= e_in_real_V_q1;
        b_imag_V_40_reg_1482 <= e_in_imag_V_15_q0;
        b_imag_V_reg_1458 <= e_in_imag_V_q0;
        b_real_V_30_reg_1476 <= e_in_real_V_15_q0;
        b_real_V_reg_1452 <= e_in_real_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        b_real_V_35_reg_1370 <= in_real_2_q0;
        in_imag_0_load_6_reg_1380 <= in_imag_0_q0;
        in_imag_0_load_reg_1340 <= in_imag_0_q1;
        in_imag_1_load_6_reg_1385 <= in_imag_1_q0;
        in_imag_1_load_reg_1345 <= in_imag_1_q1;
        in_imag_2_load_6_reg_1390 <= in_imag_2_q0;
        in_imag_2_load_reg_1350 <= in_imag_2_q1;
        in_imag_3_load_6_reg_1395 <= in_imag_3_q0;
        in_imag_3_load_reg_1355 <= in_imag_3_q1;
        in_real_0_load_6_reg_1360 <= in_real_0_q0;
        in_real_0_load_reg_1320 <= in_real_0_q1;
        in_real_1_load_6_reg_1365 <= in_real_1_q0;
        in_real_1_load_reg_1325 <= in_real_1_q1;
        in_real_2_load_reg_1330 <= in_real_2_q1;
        in_real_3_load_6_reg_1375 <= in_real_3_q0;
        in_real_3_load_reg_1335 <= in_real_3_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        r_imag_V_106_reg_1543 <= r_imag_V_106_fu_797_p2;
        r_imag_V_107_reg_1553 <= r_imag_V_107_fu_811_p2;
        r_imag_V_108_reg_1563 <= r_imag_V_108_fu_825_p2;
        r_imag_V_135_reg_1573 <= r_imag_V_135_fu_839_p2;
        r_imag_V_136_reg_1583 <= r_imag_V_136_fu_853_p2;
        r_imag_V_137_reg_1593 <= r_imag_V_137_fu_867_p2;
        r_imag_V_138_reg_1603 <= r_imag_V_138_fu_881_p2;
        r_imag_V_reg_1533 <= r_imag_V_fu_783_p2;
        r_real_V_120_reg_1568 <= r_real_V_120_fu_832_p2;
        r_real_V_121_reg_1578 <= r_real_V_121_fu_846_p2;
        r_real_V_122_reg_1588 <= r_real_V_122_fu_860_p2;
        r_real_V_123_reg_1598 <= r_real_V_123_fu_874_p2;
        r_real_V_93_reg_1538 <= r_real_V_93_fu_790_p2;
        r_real_V_94_reg_1548 <= r_real_V_94_fu_804_p2;
        r_real_V_95_reg_1558 <= r_real_V_95_fu_818_p2;
        r_real_V_reg_1528 <= r_real_V_fu_776_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        r_imag_V_141_reg_1613 <= r_imag_V_141_fu_991_p2;
        r_imag_V_142_reg_1623 <= r_imag_V_142_fu_1005_p2;
        r_imag_V_143_reg_1633 <= r_imag_V_143_fu_1019_p2;
        r_imag_V_144_reg_1643 <= r_imag_V_144_fu_1033_p2;
        r_imag_V_147_reg_1653 <= r_imag_V_147_fu_1095_p2;
        r_imag_V_148_reg_1663 <= r_imag_V_148_fu_1109_p2;
        r_imag_V_149_reg_1673 <= r_imag_V_149_fu_1123_p2;
        r_imag_V_150_reg_1683 <= r_imag_V_150_fu_1137_p2;
        r_real_V_126_reg_1608 <= r_real_V_126_fu_984_p2;
        r_real_V_127_reg_1618 <= r_real_V_127_fu_998_p2;
        r_real_V_128_reg_1628 <= r_real_V_128_fu_1012_p2;
        r_real_V_129_reg_1638 <= r_real_V_129_fu_1026_p2;
        r_real_V_132_reg_1648 <= r_real_V_132_fu_1088_p2;
        r_real_V_133_reg_1658 <= r_real_V_133_fu_1102_p2;
        r_real_V_134_reg_1668 <= r_real_V_134_fu_1116_p2;
        r_real_V_135_reg_1678 <= r_real_V_135_fu_1130_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state5_on_subcall_done)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        e_in_imag_V_15_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        e_in_imag_V_15_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_15_address0;
    end else begin
        e_in_imag_V_15_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        e_in_imag_V_15_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        e_in_imag_V_15_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_15_ce0;
    end else begin
        e_in_imag_V_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        e_in_imag_V_15_ce1 = 1'b1;
    end else begin
        e_in_imag_V_15_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        e_in_imag_V_15_we0 = grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_15_we0;
    end else begin
        e_in_imag_V_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        e_in_imag_V_16_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        e_in_imag_V_16_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_16_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        e_in_imag_V_16_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_imag_V_16_address0;
    end else begin
        e_in_imag_V_16_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        e_in_imag_V_16_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        e_in_imag_V_16_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_16_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        e_in_imag_V_16_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_imag_V_16_ce0;
    end else begin
        e_in_imag_V_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        e_in_imag_V_16_ce1 = 1'b1;
    end else begin
        e_in_imag_V_16_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        e_in_imag_V_16_we0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_imag_V_16_we0;
    end else begin
        e_in_imag_V_16_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        e_in_imag_V_17_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        e_in_imag_V_17_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_17_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        e_in_imag_V_17_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_imag_V_17_address0;
    end else begin
        e_in_imag_V_17_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        e_in_imag_V_17_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        e_in_imag_V_17_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_17_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        e_in_imag_V_17_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_imag_V_17_ce0;
    end else begin
        e_in_imag_V_17_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        e_in_imag_V_17_ce1 = 1'b1;
    end else begin
        e_in_imag_V_17_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        e_in_imag_V_17_we0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_imag_V_17_we0;
    end else begin
        e_in_imag_V_17_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        e_in_imag_V_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        e_in_imag_V_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_address0;
    end else begin
        e_in_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        e_in_imag_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        e_in_imag_V_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_ce0;
    end else begin
        e_in_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        e_in_imag_V_ce1 = 1'b1;
    end else begin
        e_in_imag_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        e_in_imag_V_we0 = grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_imag_V_we0;
    end else begin
        e_in_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        e_in_real_V_15_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        e_in_real_V_15_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_15_address0;
    end else begin
        e_in_real_V_15_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        e_in_real_V_15_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        e_in_real_V_15_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_15_ce0;
    end else begin
        e_in_real_V_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        e_in_real_V_15_ce1 = 1'b1;
    end else begin
        e_in_real_V_15_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        e_in_real_V_15_we0 = grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_15_we0;
    end else begin
        e_in_real_V_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        e_in_real_V_16_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        e_in_real_V_16_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_16_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        e_in_real_V_16_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_real_V_16_address0;
    end else begin
        e_in_real_V_16_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        e_in_real_V_16_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        e_in_real_V_16_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_16_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        e_in_real_V_16_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_real_V_16_ce0;
    end else begin
        e_in_real_V_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        e_in_real_V_16_ce1 = 1'b1;
    end else begin
        e_in_real_V_16_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        e_in_real_V_16_we0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_real_V_16_we0;
    end else begin
        e_in_real_V_16_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        e_in_real_V_17_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        e_in_real_V_17_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_17_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        e_in_real_V_17_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_real_V_17_address0;
    end else begin
        e_in_real_V_17_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        e_in_real_V_17_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        e_in_real_V_17_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_17_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        e_in_real_V_17_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_real_V_17_ce0;
    end else begin
        e_in_real_V_17_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        e_in_real_V_17_ce1 = 1'b1;
    end else begin
        e_in_real_V_17_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        e_in_real_V_17_we0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_e_in_real_V_17_we0;
    end else begin
        e_in_real_V_17_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        e_in_real_V_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        e_in_real_V_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_address0;
    end else begin
        e_in_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        e_in_real_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        e_in_real_V_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_ce0;
    end else begin
        e_in_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        e_in_real_V_ce1 = 1'b1;
    end else begin
        e_in_real_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        e_in_real_V_we0 = grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_e_in_real_V_we0;
    end else begin
        e_in_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        e_out_imag_V_1_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_e_out_imag_V_11_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        e_out_imag_V_1_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_11_address0;
    end else begin
        e_out_imag_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        e_out_imag_V_1_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_e_out_imag_V_11_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        e_out_imag_V_1_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_11_ce0;
    end else begin
        e_out_imag_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        e_out_imag_V_1_ce1 = grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_11_ce1;
    end else begin
        e_out_imag_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        e_out_imag_V_1_we0 = grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_11_we0;
    end else begin
        e_out_imag_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        e_out_imag_V_1_we1 = grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_11_we1;
    end else begin
        e_out_imag_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        e_out_imag_V_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_e_out_imag_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        e_out_imag_V_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_address0;
    end else begin
        e_out_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        e_out_imag_V_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_e_out_imag_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        e_out_imag_V_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_ce0;
    end else begin
        e_out_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        e_out_imag_V_ce1 = grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_ce1;
    end else begin
        e_out_imag_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        e_out_imag_V_we0 = grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_we0;
    end else begin
        e_out_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        e_out_imag_V_we1 = grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_imag_V_we1;
    end else begin
        e_out_imag_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        e_out_real_V_1_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_e_out_real_V_11_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        e_out_real_V_1_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_11_address0;
    end else begin
        e_out_real_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        e_out_real_V_1_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_e_out_real_V_11_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        e_out_real_V_1_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_11_ce0;
    end else begin
        e_out_real_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        e_out_real_V_1_ce1 = grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_11_ce1;
    end else begin
        e_out_real_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        e_out_real_V_1_we0 = grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_11_we0;
    end else begin
        e_out_real_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        e_out_real_V_1_we1 = grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_11_we1;
    end else begin
        e_out_real_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        e_out_real_V_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_e_out_real_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        e_out_real_V_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_address0;
    end else begin
        e_out_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        e_out_real_V_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_e_out_real_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        e_out_real_V_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_ce0;
    end else begin
        e_out_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        e_out_real_V_ce1 = grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_ce1;
    end else begin
        e_out_real_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        e_out_real_V_we0 = grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_we0;
    end else begin
        e_out_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        e_out_real_V_we1 = grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_e_out_real_V_we1;
    end else begin
        e_out_real_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_imag_0_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_imag_0_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_imag_0_address0;
    end else begin
        in_imag_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_imag_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_imag_0_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_imag_0_ce0;
    end else begin
        in_imag_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_imag_0_ce1 = 1'b1;
    end else begin
        in_imag_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_imag_1_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_imag_1_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_imag_1_address0;
    end else begin
        in_imag_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_imag_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_imag_1_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_imag_1_ce0;
    end else begin
        in_imag_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_imag_1_ce1 = 1'b1;
    end else begin
        in_imag_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_imag_2_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_imag_2_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_imag_2_address0;
    end else begin
        in_imag_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_imag_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_imag_2_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_imag_2_ce0;
    end else begin
        in_imag_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_imag_2_ce1 = 1'b1;
    end else begin
        in_imag_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_imag_3_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_imag_3_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_imag_3_address0;
    end else begin
        in_imag_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_imag_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_imag_3_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_imag_3_ce0;
    end else begin
        in_imag_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_imag_3_ce1 = 1'b1;
    end else begin
        in_imag_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_real_0_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_real_0_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_real_0_address0;
    end else begin
        in_real_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_real_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_real_0_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_real_0_ce0;
    end else begin
        in_real_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_real_0_ce1 = 1'b1;
    end else begin
        in_real_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_real_1_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_real_1_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_real_1_address0;
    end else begin
        in_real_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_real_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_real_1_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_real_1_ce0;
    end else begin
        in_real_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_real_1_ce1 = 1'b1;
    end else begin
        in_real_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_real_2_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_real_2_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_real_2_address0;
    end else begin
        in_real_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_real_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_real_2_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_real_2_ce0;
    end else begin
        in_real_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_real_2_ce1 = 1'b1;
    end else begin
        in_real_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_real_3_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_real_3_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_real_3_address0;
    end else begin
        in_real_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_real_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        in_real_3_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_in_real_3_ce0;
    end else begin
        in_real_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_real_3_ce1 = 1'b1;
    end else begin
        in_real_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state5_on_subcall_done = ((grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_ap_done == 1'b0) | (grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_ap_done == 1'b0));
end

assign cmd_imag_V_1_fu_1082_p2 = (grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_imag_V_6_out - grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_imag_V_out);

assign cmd_imag_V_fu_978_p2 = (grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_imag_V_5_out - grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_imag_V_7_out);

assign cmd_real_V_1_fu_1076_p2 = (grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_real_V_6_out - grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_real_V_out);

assign cmd_real_V_fu_972_p2 = (grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_real_V_5_out - grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_real_V_7_out);

assign cpd_imag_V_1_fu_1070_p2 = (grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_imag_V_6_out + grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_imag_V_out);

assign cpd_imag_V_fu_966_p2 = (grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_imag_V_7_out + grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_imag_V_5_out);

assign cpd_real_V_1_fu_1064_p2 = (grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_real_V_6_out + grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_real_V_out);

assign cpd_real_V_fu_960_p2 = (grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_real_V_7_out + grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_real_V_5_out);

assign e_in_imag_V_15_address1 = 64'd0;

assign e_in_imag_V_16_address1 = 64'd1;

assign e_in_imag_V_17_address1 = 64'd1;

assign e_in_imag_V_address1 = 64'd0;

assign e_in_real_V_15_address1 = 64'd0;

assign e_in_real_V_16_address1 = 64'd1;

assign e_in_real_V_17_address1 = 64'd1;

assign e_in_real_V_address1 = 64'd0;

assign grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_ap_start = grp_fft_16pt_Pipeline_VITIS_LOOP_120_1_fu_608_ap_start_reg;

assign grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_ap_start = grp_fft_16pt_Pipeline_VITIS_LOOP_131_2_fu_672_ap_start_reg;

assign grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_ap_start = grp_fft_16pt_Pipeline_VITIS_LOOP_165_1_fu_580_ap_start_reg;

assign grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_ap_start = grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_ap_start_reg;

assign grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_ap_start = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_ap_start_reg;

assign in_imag_0_address1 = 64'd1;

assign in_imag_1_address1 = 64'd1;

assign in_imag_2_address1 = 64'd1;

assign in_imag_3_address1 = 64'd1;

assign in_real_0_address1 = 64'd1;

assign in_real_1_address1 = 64'd1;

assign in_real_2_address1 = 64'd1;

assign in_real_3_address1 = 64'd1;

assign out_imag_0_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_0_address0;

assign out_imag_0_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_0_ce0;

assign out_imag_0_d0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_0_d0;

assign out_imag_0_we0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_0_we0;

assign out_imag_1_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_1_address0;

assign out_imag_1_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_1_ce0;

assign out_imag_1_d0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_1_d0;

assign out_imag_1_we0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_1_we0;

assign out_imag_2_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_2_address0;

assign out_imag_2_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_2_ce0;

assign out_imag_2_d0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_2_d0;

assign out_imag_2_we0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_2_we0;

assign out_imag_3_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_3_address0;

assign out_imag_3_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_3_ce0;

assign out_imag_3_d0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_3_d0;

assign out_imag_3_we0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_imag_3_we0;

assign out_real_0_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_0_address0;

assign out_real_0_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_0_ce0;

assign out_real_0_d0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_0_d0;

assign out_real_0_we0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_0_we0;

assign out_real_1_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_1_address0;

assign out_real_1_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_1_ce0;

assign out_real_1_d0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_1_d0;

assign out_real_1_we0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_1_we0;

assign out_real_2_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_2_address0;

assign out_real_2_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_2_ce0;

assign out_real_2_d0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_2_d0;

assign out_real_2_we0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_2_we0;

assign out_real_3_address0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_3_address0;

assign out_real_3_ce0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_3_ce0;

assign out_real_3_d0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_3_d0;

assign out_real_3_we0 = grp_fft_16pt_Pipeline_VITIS_LOOP_181_3_fu_700_out_real_3_we0;

assign r_imag_V_106_fu_797_p2 = (r_imag_V_132_fu_756_p2 - r_real_V_119_fu_768_p2);

assign r_imag_V_107_fu_811_p2 = (r_imag_V_131_fu_748_p2 - r_imag_V_133_fu_764_p2);

assign r_imag_V_108_fu_825_p2 = (r_real_V_119_fu_768_p2 + r_imag_V_132_fu_756_p2);

assign r_imag_V_131_fu_748_p2 = (b_imag_V_reg_1458 + a_imag_V_reg_1446);

assign r_imag_V_132_fu_756_p2 = (a_imag_V_reg_1446 - b_imag_V_reg_1458);

assign r_imag_V_133_fu_764_p2 = (b_imag_V_40_reg_1482 + a_imag_V_36_reg_1470);

assign r_imag_V_134_fu_772_p2 = (a_imag_V_36_reg_1470 - b_imag_V_40_reg_1482);

assign r_imag_V_135_fu_839_p2 = (e_in_imag_V_17_q1 + e_in_imag_V_16_q1);

assign r_imag_V_136_fu_853_p2 = (e_in_imag_V_16_q1 - e_in_imag_V_17_q1);

assign r_imag_V_137_fu_867_p2 = (e_in_imag_V_17_q0 + e_in_imag_V_16_q0);

assign r_imag_V_138_fu_881_p2 = (e_in_imag_V_16_q0 - e_in_imag_V_17_q0);

assign r_imag_V_139_fu_942_p2 = (grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_imag_V_6_out + grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_imag_V_out);

assign r_imag_V_140_fu_954_p2 = (grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_imag_V_out - grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_imag_V_6_out);

assign r_imag_V_141_fu_991_p2 = (cpd_imag_V_fu_966_p2 + r_imag_V_139_fu_942_p2);

assign r_imag_V_142_fu_1005_p2 = (r_imag_V_140_fu_954_p2 - cmd_real_V_fu_972_p2);

assign r_imag_V_143_fu_1019_p2 = (r_imag_V_139_fu_942_p2 - cpd_imag_V_fu_966_p2);

assign r_imag_V_144_fu_1033_p2 = (r_imag_V_140_fu_954_p2 + cmd_real_V_fu_972_p2);

assign r_imag_V_145_fu_1046_p2 = (grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_imag_V_7_out + grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_imag_V_5_out);

assign r_imag_V_146_fu_1058_p2 = (grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_imag_V_7_out - grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_imag_V_5_out);

assign r_imag_V_147_fu_1095_p2 = (r_imag_V_145_fu_1046_p2 + cpd_imag_V_1_fu_1070_p2);

assign r_imag_V_148_fu_1109_p2 = (r_imag_V_146_fu_1058_p2 - cmd_real_V_1_fu_1076_p2);

assign r_imag_V_149_fu_1123_p2 = (r_imag_V_145_fu_1046_p2 - cpd_imag_V_1_fu_1070_p2);

assign r_imag_V_150_fu_1137_p2 = (cmd_real_V_1_fu_1076_p2 + r_imag_V_146_fu_1058_p2);

assign r_imag_V_fu_783_p2 = (r_imag_V_133_fu_764_p2 + r_imag_V_131_fu_748_p2);

assign r_real_V_116_fu_744_p2 = (b_real_V_reg_1452 + a_real_V_reg_1440);

assign r_real_V_117_fu_752_p2 = (a_real_V_reg_1440 - b_real_V_reg_1452);

assign r_real_V_118_fu_760_p2 = (b_real_V_30_reg_1476 + a_real_V_41_reg_1464);

assign r_real_V_119_fu_768_p2 = (a_real_V_41_reg_1464 - b_real_V_30_reg_1476);

assign r_real_V_120_fu_832_p2 = (e_in_real_V_17_q1 + e_in_real_V_16_q1);

assign r_real_V_121_fu_846_p2 = (e_in_real_V_16_q1 - e_in_real_V_17_q1);

assign r_real_V_122_fu_860_p2 = (e_in_real_V_17_q0 + e_in_real_V_16_q0);

assign r_real_V_123_fu_874_p2 = (e_in_real_V_16_q0 - e_in_real_V_17_q0);

assign r_real_V_124_fu_936_p2 = (grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_real_V_6_out + grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_real_V_out);

assign r_real_V_125_fu_948_p2 = (grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_real_V_out - grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o1_in_real_V_6_out);

assign r_real_V_126_fu_984_p2 = (cpd_real_V_fu_960_p2 + r_real_V_124_fu_936_p2);

assign r_real_V_127_fu_998_p2 = (cmd_imag_V_fu_978_p2 + r_real_V_125_fu_948_p2);

assign r_real_V_128_fu_1012_p2 = (r_real_V_124_fu_936_p2 - cpd_real_V_fu_960_p2);

assign r_real_V_129_fu_1026_p2 = (r_real_V_125_fu_948_p2 - cmd_imag_V_fu_978_p2);

assign r_real_V_130_fu_1040_p2 = (grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_real_V_7_out + grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_real_V_5_out);

assign r_real_V_131_fu_1052_p2 = (grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_real_V_7_out - grp_fft_16pt_Pipeline_VITIS_LOOP_171_2_fu_620_o2_in_real_V_5_out);

assign r_real_V_132_fu_1088_p2 = (r_real_V_130_fu_1040_p2 + cpd_real_V_1_fu_1064_p2);

assign r_real_V_133_fu_1102_p2 = (r_real_V_131_fu_1052_p2 + cmd_imag_V_1_fu_1082_p2);

assign r_real_V_134_fu_1116_p2 = (r_real_V_130_fu_1040_p2 - cpd_real_V_1_fu_1064_p2);

assign r_real_V_135_fu_1130_p2 = (r_real_V_131_fu_1052_p2 - cmd_imag_V_1_fu_1082_p2);

assign r_real_V_93_fu_790_p2 = (r_imag_V_134_fu_772_p2 + r_real_V_117_fu_752_p2);

assign r_real_V_94_fu_804_p2 = (r_real_V_116_fu_744_p2 - r_real_V_118_fu_760_p2);

assign r_real_V_95_fu_818_p2 = (r_real_V_117_fu_752_p2 - r_imag_V_134_fu_772_p2);

assign r_real_V_fu_776_p2 = (r_real_V_118_fu_760_p2 + r_real_V_116_fu_744_p2);

endmodule //sr_fft_fft_16pt
