
log_wave -r /
set designtopgroup [add_wave_group "Design Top Signals"]
set cinoutgroup [add_wave_group "C InOuts" -into $designtopgroup]
set input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group [add_wave_group input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return(axi_slave) -into $cinoutgroup]
add_wave /apatb_sr_fft_top/AESL_inst_sr_fft/interrupt -into $input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -color #ffff00 -radix hex
add_wave /apatb_sr_fft_top/AESL_inst_sr_fft/s_axi_control_BRESP -into $input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -radix hex
add_wave /apatb_sr_fft_top/AESL_inst_sr_fft/s_axi_control_BREADY -into $input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -color #ffff00 -radix hex
add_wave /apatb_sr_fft_top/AESL_inst_sr_fft/s_axi_control_BVALID -into $input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -color #ffff00 -radix hex
add_wave /apatb_sr_fft_top/AESL_inst_sr_fft/s_axi_control_RRESP -into $input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -radix hex
add_wave /apatb_sr_fft_top/AESL_inst_sr_fft/s_axi_control_RDATA -into $input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -radix hex
add_wave /apatb_sr_fft_top/AESL_inst_sr_fft/s_axi_control_RREADY -into $input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -color #ffff00 -radix hex
add_wave /apatb_sr_fft_top/AESL_inst_sr_fft/s_axi_control_RVALID -into $input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -color #ffff00 -radix hex
add_wave /apatb_sr_fft_top/AESL_inst_sr_fft/s_axi_control_ARREADY -into $input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -color #ffff00 -radix hex
add_wave /apatb_sr_fft_top/AESL_inst_sr_fft/s_axi_control_ARVALID -into $input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -color #ffff00 -radix hex
add_wave /apatb_sr_fft_top/AESL_inst_sr_fft/s_axi_control_ARADDR -into $input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -radix hex
add_wave /apatb_sr_fft_top/AESL_inst_sr_fft/s_axi_control_WSTRB -into $input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -radix hex
add_wave /apatb_sr_fft_top/AESL_inst_sr_fft/s_axi_control_WDATA -into $input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -radix hex
add_wave /apatb_sr_fft_top/AESL_inst_sr_fft/s_axi_control_WREADY -into $input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -color #ffff00 -radix hex
add_wave /apatb_sr_fft_top/AESL_inst_sr_fft/s_axi_control_WVALID -into $input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -color #ffff00 -radix hex
add_wave /apatb_sr_fft_top/AESL_inst_sr_fft/s_axi_control_AWREADY -into $input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -color #ffff00 -radix hex
add_wave /apatb_sr_fft_top/AESL_inst_sr_fft/s_axi_control_AWVALID -into $input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -color #ffff00 -radix hex
add_wave /apatb_sr_fft_top/AESL_inst_sr_fft/s_axi_control_AWADDR -into $input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -radix hex
set blocksiggroup [add_wave_group "Block-level IO Handshake(internal)" -into $designtopgroup]
add_wave /apatb_sr_fft_top/AESL_inst_sr_fft/ap_done -into $blocksiggroup
add_wave /apatb_sr_fft_top/AESL_inst_sr_fft/ap_idle -into $blocksiggroup
add_wave /apatb_sr_fft_top/AESL_inst_sr_fft/ap_ready -into $blocksiggroup
add_wave /apatb_sr_fft_top/AESL_inst_sr_fft/ap_start -into $blocksiggroup
set resetgroup [add_wave_group "Reset" -into $designtopgroup]
add_wave /apatb_sr_fft_top/AESL_inst_sr_fft/ap_rst_n -into $resetgroup
set clockgroup [add_wave_group "Clock" -into $designtopgroup]
add_wave /apatb_sr_fft_top/AESL_inst_sr_fft/ap_clk -into $clockgroup
set testbenchgroup [add_wave_group "Test Bench Signals"]
set tbinternalsiggroup [add_wave_group "Internal Signals" -into $testbenchgroup]
set tb_simstatus_group [add_wave_group "Simulation Status" -into $tbinternalsiggroup]
set tb_portdepth_group [add_wave_group "Port Depth" -into $tbinternalsiggroup]
add_wave /apatb_sr_fft_top/AUTOTB_TRANSACTION_NUM -into $tb_simstatus_group -radix hex
add_wave /apatb_sr_fft_top/ready_cnt -into $tb_simstatus_group -radix hex
add_wave /apatb_sr_fft_top/done_cnt -into $tb_simstatus_group -radix hex
add_wave /apatb_sr_fft_top/LENGTH_input_0 -into $tb_portdepth_group -radix hex
add_wave /apatb_sr_fft_top/LENGTH_input_1 -into $tb_portdepth_group -radix hex
add_wave /apatb_sr_fft_top/LENGTH_input_2 -into $tb_portdepth_group -radix hex
add_wave /apatb_sr_fft_top/LENGTH_input_3 -into $tb_portdepth_group -radix hex
add_wave /apatb_sr_fft_top/LENGTH_input_4 -into $tb_portdepth_group -radix hex
add_wave /apatb_sr_fft_top/LENGTH_input_5 -into $tb_portdepth_group -radix hex
add_wave /apatb_sr_fft_top/LENGTH_input_6 -into $tb_portdepth_group -radix hex
add_wave /apatb_sr_fft_top/LENGTH_input_7 -into $tb_portdepth_group -radix hex
add_wave /apatb_sr_fft_top/LENGTH_output_0 -into $tb_portdepth_group -radix hex
add_wave /apatb_sr_fft_top/LENGTH_output_1 -into $tb_portdepth_group -radix hex
add_wave /apatb_sr_fft_top/LENGTH_output_2 -into $tb_portdepth_group -radix hex
add_wave /apatb_sr_fft_top/LENGTH_output_3 -into $tb_portdepth_group -radix hex
add_wave /apatb_sr_fft_top/LENGTH_output_4 -into $tb_portdepth_group -radix hex
add_wave /apatb_sr_fft_top/LENGTH_output_5 -into $tb_portdepth_group -radix hex
add_wave /apatb_sr_fft_top/LENGTH_output_6 -into $tb_portdepth_group -radix hex
add_wave /apatb_sr_fft_top/LENGTH_output_7 -into $tb_portdepth_group -radix hex
set tbcinoutgroup [add_wave_group "C InOuts" -into $testbenchgroup]
set tb_input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group [add_wave_group input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return(axi_slave) -into $tbcinoutgroup]
add_wave /apatb_sr_fft_top/control_INTERRUPT -into $tb_input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -color #ffff00 -radix hex
add_wave /apatb_sr_fft_top/control_BRESP -into $tb_input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -radix hex
add_wave /apatb_sr_fft_top/control_BREADY -into $tb_input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -color #ffff00 -radix hex
add_wave /apatb_sr_fft_top/control_BVALID -into $tb_input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -color #ffff00 -radix hex
add_wave /apatb_sr_fft_top/control_RRESP -into $tb_input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -radix hex
add_wave /apatb_sr_fft_top/control_RDATA -into $tb_input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -radix hex
add_wave /apatb_sr_fft_top/control_RREADY -into $tb_input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -color #ffff00 -radix hex
add_wave /apatb_sr_fft_top/control_RVALID -into $tb_input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -color #ffff00 -radix hex
add_wave /apatb_sr_fft_top/control_ARREADY -into $tb_input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -color #ffff00 -radix hex
add_wave /apatb_sr_fft_top/control_ARVALID -into $tb_input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -color #ffff00 -radix hex
add_wave /apatb_sr_fft_top/control_ARADDR -into $tb_input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -radix hex
add_wave /apatb_sr_fft_top/control_WSTRB -into $tb_input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -radix hex
add_wave /apatb_sr_fft_top/control_WDATA -into $tb_input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -radix hex
add_wave /apatb_sr_fft_top/control_WREADY -into $tb_input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -color #ffff00 -radix hex
add_wave /apatb_sr_fft_top/control_WVALID -into $tb_input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -color #ffff00 -radix hex
add_wave /apatb_sr_fft_top/control_AWREADY -into $tb_input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -color #ffff00 -radix hex
add_wave /apatb_sr_fft_top/control_AWVALID -into $tb_input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -color #ffff00 -radix hex
add_wave /apatb_sr_fft_top/control_AWADDR -into $tb_input_0__input_1__input_2__input_3__input_4__input_5__input_6__input_7__output_0__output_1__output_2__output_3__output_4__output_5__output_6__output_7__return_group -radix hex
save_wave_config sr_fft.wcfg
run all
quit

