// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sr_fft_fft_32pt_Pipeline_VITIS_LOOP_215_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        e_in_imag_V_14_address0,
        e_in_imag_V_14_ce0,
        e_in_imag_V_14_we0,
        e_in_imag_V_14_d0,
        e_in_imag_V_13_address0,
        e_in_imag_V_13_ce0,
        e_in_imag_V_13_we0,
        e_in_imag_V_13_d0,
        e_in_imag_V_12_address0,
        e_in_imag_V_12_ce0,
        e_in_imag_V_12_we0,
        e_in_imag_V_12_d0,
        e_in_imag_V_11_address0,
        e_in_imag_V_11_ce0,
        e_in_imag_V_11_we0,
        e_in_imag_V_11_d0,
        e_in_real_V_14_address0,
        e_in_real_V_14_ce0,
        e_in_real_V_14_we0,
        e_in_real_V_14_d0,
        e_in_real_V_13_address0,
        e_in_real_V_13_ce0,
        e_in_real_V_13_we0,
        e_in_real_V_13_d0,
        e_in_real_V_12_address0,
        e_in_real_V_12_ce0,
        e_in_real_V_12_we0,
        e_in_real_V_12_d0,
        e_in_real_V_11_address0,
        e_in_real_V_11_ce0,
        e_in_real_V_11_we0,
        e_in_real_V_11_d0,
        in_real_0_address0,
        in_real_0_ce0,
        in_real_0_q0,
        in_real_1_address0,
        in_real_1_ce0,
        in_real_1_q0,
        in_real_2_address0,
        in_real_2_ce0,
        in_real_2_q0,
        in_real_3_address0,
        in_real_3_ce0,
        in_real_3_q0,
        in_real_4_address0,
        in_real_4_ce0,
        in_real_4_q0,
        in_real_5_address0,
        in_real_5_ce0,
        in_real_5_q0,
        in_real_6_address0,
        in_real_6_ce0,
        in_real_6_q0,
        in_real_7_address0,
        in_real_7_ce0,
        in_real_7_q0,
        in_imag_0_address0,
        in_imag_0_ce0,
        in_imag_0_q0,
        in_imag_1_address0,
        in_imag_1_ce0,
        in_imag_1_q0,
        in_imag_2_address0,
        in_imag_2_ce0,
        in_imag_2_q0,
        in_imag_3_address0,
        in_imag_3_ce0,
        in_imag_3_q0,
        in_imag_4_address0,
        in_imag_4_ce0,
        in_imag_4_q0,
        in_imag_5_address0,
        in_imag_5_ce0,
        in_imag_5_q0,
        in_imag_6_address0,
        in_imag_6_ce0,
        in_imag_6_q0,
        in_imag_7_address0,
        in_imag_7_ce0,
        in_imag_7_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [1:0] e_in_imag_V_14_address0;
output   e_in_imag_V_14_ce0;
output   e_in_imag_V_14_we0;
output  [31:0] e_in_imag_V_14_d0;
output  [1:0] e_in_imag_V_13_address0;
output   e_in_imag_V_13_ce0;
output   e_in_imag_V_13_we0;
output  [31:0] e_in_imag_V_13_d0;
output  [1:0] e_in_imag_V_12_address0;
output   e_in_imag_V_12_ce0;
output   e_in_imag_V_12_we0;
output  [31:0] e_in_imag_V_12_d0;
output  [1:0] e_in_imag_V_11_address0;
output   e_in_imag_V_11_ce0;
output   e_in_imag_V_11_we0;
output  [31:0] e_in_imag_V_11_d0;
output  [1:0] e_in_real_V_14_address0;
output   e_in_real_V_14_ce0;
output   e_in_real_V_14_we0;
output  [31:0] e_in_real_V_14_d0;
output  [1:0] e_in_real_V_13_address0;
output   e_in_real_V_13_ce0;
output   e_in_real_V_13_we0;
output  [31:0] e_in_real_V_13_d0;
output  [1:0] e_in_real_V_12_address0;
output   e_in_real_V_12_ce0;
output   e_in_real_V_12_we0;
output  [31:0] e_in_real_V_12_d0;
output  [1:0] e_in_real_V_11_address0;
output   e_in_real_V_11_ce0;
output   e_in_real_V_11_we0;
output  [31:0] e_in_real_V_11_d0;
output  [1:0] in_real_0_address0;
output   in_real_0_ce0;
input  [31:0] in_real_0_q0;
output  [1:0] in_real_1_address0;
output   in_real_1_ce0;
input  [31:0] in_real_1_q0;
output  [1:0] in_real_2_address0;
output   in_real_2_ce0;
input  [31:0] in_real_2_q0;
output  [1:0] in_real_3_address0;
output   in_real_3_ce0;
input  [31:0] in_real_3_q0;
output  [1:0] in_real_4_address0;
output   in_real_4_ce0;
input  [31:0] in_real_4_q0;
output  [1:0] in_real_5_address0;
output   in_real_5_ce0;
input  [31:0] in_real_5_q0;
output  [1:0] in_real_6_address0;
output   in_real_6_ce0;
input  [31:0] in_real_6_q0;
output  [1:0] in_real_7_address0;
output   in_real_7_ce0;
input  [31:0] in_real_7_q0;
output  [1:0] in_imag_0_address0;
output   in_imag_0_ce0;
input  [31:0] in_imag_0_q0;
output  [1:0] in_imag_1_address0;
output   in_imag_1_ce0;
input  [31:0] in_imag_1_q0;
output  [1:0] in_imag_2_address0;
output   in_imag_2_ce0;
input  [31:0] in_imag_2_q0;
output  [1:0] in_imag_3_address0;
output   in_imag_3_ce0;
input  [31:0] in_imag_3_q0;
output  [1:0] in_imag_4_address0;
output   in_imag_4_ce0;
input  [31:0] in_imag_4_q0;
output  [1:0] in_imag_5_address0;
output   in_imag_5_ce0;
input  [31:0] in_imag_5_q0;
output  [1:0] in_imag_6_address0;
output   in_imag_6_ce0;
input  [31:0] in_imag_6_q0;
output  [1:0] in_imag_7_address0;
output   in_imag_7_ce0;
input  [31:0] in_imag_7_q0;

reg ap_idle;
reg e_in_imag_V_14_ce0;
reg e_in_imag_V_14_we0;
reg e_in_imag_V_13_ce0;
reg e_in_imag_V_13_we0;
reg e_in_imag_V_12_ce0;
reg e_in_imag_V_12_we0;
reg e_in_imag_V_11_ce0;
reg e_in_imag_V_11_we0;
reg e_in_real_V_14_ce0;
reg e_in_real_V_14_we0;
reg e_in_real_V_13_ce0;
reg e_in_real_V_13_we0;
reg e_in_real_V_12_ce0;
reg e_in_real_V_12_we0;
reg e_in_real_V_11_ce0;
reg e_in_real_V_11_we0;
reg in_real_0_ce0;
reg in_real_1_ce0;
reg in_real_2_ce0;
reg in_real_3_ce0;
reg in_real_4_ce0;
reg in_real_5_ce0;
reg in_real_6_ce0;
reg in_real_7_ce0;
reg in_imag_0_ce0;
reg in_imag_1_ce0;
reg in_imag_2_ce0;
reg in_imag_3_ce0;
reg in_imag_4_ce0;
reg in_imag_5_ce0;
reg in_imag_6_ce0;
reg in_imag_7_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln215_fu_416_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [4:0] i_4_reg_558;
wire    ap_block_pp0_stage0_11001;
reg   [1:0] trunc_ln217_1_reg_647;
wire   [63:0] zext_ln217_fu_440_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln217_1_fu_478_p1;
reg   [4:0] i_fu_92;
wire   [4:0] add_ln215_fu_422_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i_4;
wire   [31:0] tmp_fu_499_p10;
wire   [31:0] tmp_s_fu_525_p10;
wire   [0:0] trunc_ln217_fu_428_p1;
wire   [1:0] shl_ln_fu_432_p3;
wire   [1:0] trunc_ln215_fu_475_p1;
wire   [2:0] tmp_fu_499_p9;
wire   [2:0] tmp_s_fu_525_p9;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

sr_fft_mux_83_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_83_32_1_1_U62(
    .din0(in_real_0_q0),
    .din1(in_real_1_q0),
    .din2(in_real_2_q0),
    .din3(in_real_3_q0),
    .din4(in_real_4_q0),
    .din5(in_real_5_q0),
    .din6(in_real_6_q0),
    .din7(in_real_7_q0),
    .din8(tmp_fu_499_p9),
    .dout(tmp_fu_499_p10)
);

sr_fft_mux_83_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_83_32_1_1_U63(
    .din0(in_imag_0_q0),
    .din1(in_imag_1_q0),
    .din2(in_imag_2_q0),
    .din3(in_imag_3_q0),
    .din4(in_imag_4_q0),
    .din5(in_imag_5_q0),
    .din6(in_imag_6_q0),
    .din7(in_imag_7_q0),
    .din8(tmp_s_fu_525_p9),
    .dout(tmp_s_fu_525_p10)
);

sr_fft_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln215_fu_416_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_92 <= add_ln215_fu_422_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_92 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_4_reg_558 <= ap_sig_allocacmp_i_4;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln215_fu_416_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln217_1_reg_647 <= {{ap_sig_allocacmp_i_4[3:2]}};
    end
end

always @ (*) begin
    if (((icmp_ln215_fu_416_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_4 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_4 = i_fu_92;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        e_in_imag_V_11_ce0 = 1'b1;
    end else begin
        e_in_imag_V_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln217_1_reg_647 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        e_in_imag_V_11_we0 = 1'b1;
    end else begin
        e_in_imag_V_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        e_in_imag_V_12_ce0 = 1'b1;
    end else begin
        e_in_imag_V_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln217_1_reg_647 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        e_in_imag_V_12_we0 = 1'b1;
    end else begin
        e_in_imag_V_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        e_in_imag_V_13_ce0 = 1'b1;
    end else begin
        e_in_imag_V_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln217_1_reg_647 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        e_in_imag_V_13_we0 = 1'b1;
    end else begin
        e_in_imag_V_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        e_in_imag_V_14_ce0 = 1'b1;
    end else begin
        e_in_imag_V_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln217_1_reg_647 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        e_in_imag_V_14_we0 = 1'b1;
    end else begin
        e_in_imag_V_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        e_in_real_V_11_ce0 = 1'b1;
    end else begin
        e_in_real_V_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln217_1_reg_647 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        e_in_real_V_11_we0 = 1'b1;
    end else begin
        e_in_real_V_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        e_in_real_V_12_ce0 = 1'b1;
    end else begin
        e_in_real_V_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln217_1_reg_647 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        e_in_real_V_12_we0 = 1'b1;
    end else begin
        e_in_real_V_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        e_in_real_V_13_ce0 = 1'b1;
    end else begin
        e_in_real_V_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln217_1_reg_647 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        e_in_real_V_13_we0 = 1'b1;
    end else begin
        e_in_real_V_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        e_in_real_V_14_ce0 = 1'b1;
    end else begin
        e_in_real_V_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln217_1_reg_647 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        e_in_real_V_14_we0 = 1'b1;
    end else begin
        e_in_real_V_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_imag_0_ce0 = 1'b1;
    end else begin
        in_imag_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_imag_1_ce0 = 1'b1;
    end else begin
        in_imag_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_imag_2_ce0 = 1'b1;
    end else begin
        in_imag_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_imag_3_ce0 = 1'b1;
    end else begin
        in_imag_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_imag_4_ce0 = 1'b1;
    end else begin
        in_imag_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_imag_5_ce0 = 1'b1;
    end else begin
        in_imag_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_imag_6_ce0 = 1'b1;
    end else begin
        in_imag_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_imag_7_ce0 = 1'b1;
    end else begin
        in_imag_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_real_0_ce0 = 1'b1;
    end else begin
        in_real_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_real_1_ce0 = 1'b1;
    end else begin
        in_real_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_real_2_ce0 = 1'b1;
    end else begin
        in_real_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_real_3_ce0 = 1'b1;
    end else begin
        in_real_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_real_4_ce0 = 1'b1;
    end else begin
        in_real_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_real_5_ce0 = 1'b1;
    end else begin
        in_real_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_real_6_ce0 = 1'b1;
    end else begin
        in_real_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_real_7_ce0 = 1'b1;
    end else begin
        in_real_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln215_fu_422_p2 = (ap_sig_allocacmp_i_4 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign e_in_imag_V_11_address0 = zext_ln217_1_fu_478_p1;

assign e_in_imag_V_11_d0 = tmp_s_fu_525_p10;

assign e_in_imag_V_12_address0 = zext_ln217_1_fu_478_p1;

assign e_in_imag_V_12_d0 = tmp_s_fu_525_p10;

assign e_in_imag_V_13_address0 = zext_ln217_1_fu_478_p1;

assign e_in_imag_V_13_d0 = tmp_s_fu_525_p10;

assign e_in_imag_V_14_address0 = zext_ln217_1_fu_478_p1;

assign e_in_imag_V_14_d0 = tmp_s_fu_525_p10;

assign e_in_real_V_11_address0 = zext_ln217_1_fu_478_p1;

assign e_in_real_V_11_d0 = tmp_fu_499_p10;

assign e_in_real_V_12_address0 = zext_ln217_1_fu_478_p1;

assign e_in_real_V_12_d0 = tmp_fu_499_p10;

assign e_in_real_V_13_address0 = zext_ln217_1_fu_478_p1;

assign e_in_real_V_13_d0 = tmp_fu_499_p10;

assign e_in_real_V_14_address0 = zext_ln217_1_fu_478_p1;

assign e_in_real_V_14_d0 = tmp_fu_499_p10;

assign icmp_ln215_fu_416_p2 = ((ap_sig_allocacmp_i_4 == 5'd16) ? 1'b1 : 1'b0);

assign in_imag_0_address0 = zext_ln217_fu_440_p1;

assign in_imag_1_address0 = zext_ln217_fu_440_p1;

assign in_imag_2_address0 = zext_ln217_fu_440_p1;

assign in_imag_3_address0 = zext_ln217_fu_440_p1;

assign in_imag_4_address0 = zext_ln217_fu_440_p1;

assign in_imag_5_address0 = zext_ln217_fu_440_p1;

assign in_imag_6_address0 = zext_ln217_fu_440_p1;

assign in_imag_7_address0 = zext_ln217_fu_440_p1;

assign in_real_0_address0 = zext_ln217_fu_440_p1;

assign in_real_1_address0 = zext_ln217_fu_440_p1;

assign in_real_2_address0 = zext_ln217_fu_440_p1;

assign in_real_3_address0 = zext_ln217_fu_440_p1;

assign in_real_4_address0 = zext_ln217_fu_440_p1;

assign in_real_5_address0 = zext_ln217_fu_440_p1;

assign in_real_6_address0 = zext_ln217_fu_440_p1;

assign in_real_7_address0 = zext_ln217_fu_440_p1;

assign shl_ln_fu_432_p3 = {{trunc_ln217_fu_428_p1}, {1'd0}};

assign tmp_fu_499_p9 = {{i_4_reg_558[3:1]}};

assign tmp_s_fu_525_p9 = {{i_4_reg_558[3:1]}};

assign trunc_ln215_fu_475_p1 = i_4_reg_558[1:0];

assign trunc_ln217_fu_428_p1 = ap_sig_allocacmp_i_4[0:0];

assign zext_ln217_1_fu_478_p1 = trunc_ln215_fu_475_p1;

assign zext_ln217_fu_440_p1 = shl_ln_fu_432_p3;

endmodule //sr_fft_fft_32pt_Pipeline_VITIS_LOOP_215_1
